project:
  type: book
  
book:
  title: "Practical Generative Art with R and ggplot2: drawing with data"
  author: "Pedro Duarte Faria"
  date: "today"


bibliography: references.bib
number-sections: true
format:
  html:
    theme: 
      - cosmo
      - theme.scss