project:
  type: book
  output-dir: docs
  
book:
  title: "Practical Generative Art with R and ggplot2: drawing with data"
  author: "Pedro Duarte Faria"
  cover-image: "Cover/cover.png"
  date: "today"
  edition: "First edition"
  chapters:
    - index.qmd
    - Chapters/01-angles.qmd
    - Chapters/01-transformations.qmd
    - Chapters/02-random.qmd
    - Chapters/03-flow-fields.qmd
    - Chapters/04-subdivisions.qmd
    - Chapters/05-fractal.qmd
    - Chapters/05-ifs.qmd
    - Chapters/06-filters.qmd
    - Chapters/_references.qmd


bibliography: references.bib
number-sections: true
format:
  html:
    theme: 
      - cosmo