project:
  type: book
  output-dir: docs
  
book:
  title: "Practical Generative Art with R and ggplot2: drawing with data"
  author: "Pedro Duarte Faria"
  date: "today"
  edition: "First edition"
  chapters:
    - index.qmd
    - Chapters/01-angles.qmd
    - Chapters/01-transformations.qmd
    - Chapters/02-random.qmd


bibliography: references.bib
number-sections: true
format:
  html:
    theme: 
      - cosmo
  pdf:
    fontfamily: "Times New Roman"
    fontsize: 11pt